# Generated by Django 3.2.7 on 2021-09-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityuser',
            name='group',
            field=models.ManyToManyField(default=None, to='app.UserGroup'),
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='app.subject'),
        ),
    ]
